siteTitle = "GraphQL Elixir"
ga = "UA-xxxxx"

[docs.quickstart]
	name = "Quickstart"
	pages = [
	  "/docs/quickstart/",
	]

[docs.walkthrough]
	name = "Walkthrough"
	pages = [
		"/docs/basic-types/",
	  "/docs/objecttypes/",
	  "/docs/mutations/",
	]

[docs.phoenix]
	name = "Phoenix"
	pages = [
	  "/docs/phoenix/tutorial/",
	]
